testing_type = "remote"
startup_script = "./debian/start_qemu.sh"
stop_script = "./debian/stop_qemu.sh"
skip_packages = ["docker"]

[connection]
method = "ssh"
ip = "192.168.31.87"
port = 22
username = "openkylin"
password = "openkylin"
