#!/bin/bash

PACKAGE_NAME="httpd"
PACKAGE_VERSION=$(rpm -qi $PACKAGE_NAME | grep Version | awk '{print $2}')
PACKAGE_PRETTY_NAME="Apache HTTP Server"
PACKAGE_TYPE="Web Server"
PACKAGE_DESCRIPTION="Apache HTTP Server"

echo $PACKAGE_VERSION
echo $PACKAGE_PRETTY_NAME
echo $PACKAGE_TYPE
echo $PACKAGE_DESCRIPTION