[package]
name = "lintestor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.13"
serde = { version = "1.0.204", features = ["derive"] }
serde_derive = "1.0.204"
serde_json = "1.0.128"
ssh2 = "0.9.4"
openssl = { version = "0.10.66", features = ["vendored"] }
toml = "0.8.15"

[profile.release]
strip = true 
lto = true
codegen-units = 1
