[package]
name = "lintestor"
version = "0.1.3"
edition = "2021"
description = "Yet another Linux package tester"
license = "MIT"
repository = "https://github.com/255doesnotexist/lintestor"

[dependencies]
clap = "4.5.21"
serde = { version = "1.0.214", features = ["derive"] }
serde_derive = "1.0.204"
serde_json = "1.0.133"
ssh2 = "0.9.4"
openssl = { version = "0.10.68", features = ["vendored"] }
toml = "0.8.19"
env_logger = "0.11.5"
log = "0.4.22"
chrono = "0.4.38"
[dev-dependencies]
assert_cmd = "2.0.16"

[profile.release]
strip = true 
lto = true
codegen-units = 1
