[package]
name = "lintestor"
version = "0.1.6"
edition = "2021"
description = "Yet another Linux package tester"
license = "MIT"
repository = "https://github.com/255doesnotexist/lintestor"

[dependencies]
clap = "4.5.30"
serde = { version = "1.0.217", features = ["derive"] }
serde_derive = "1.0.204"
serde_json = "1.0.139"
ssh2 = "0.9.5"
openssl = { version = "0.10.71", features = ["vendored"] }
toml = "0.8.20"
env_logger = "0.11.6"
log = "0.4.25"
chrono = "0.4.39"
dirs = "6.0.0"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
base64 = "0.22.1"
anyhow = "1.0.95"
async-trait = "0.1.86"
dialoguer = "0.11.0"
[dev-dependencies]
assert_cmd = "2.0.16"

[profile.release]
strip = true 
lto = true
codegen-units = 1
