enabled = true
testing_type = "qemu-based-remote"
startup_script = "./fedora/start_qemu.sh"
stop_script = "./fedora/stop_qemu.sh"
skip_packages = ["docker"]

[connection]
method = "ssh"
ip = "localhost"
port = 2223
username = "fedora"
password = "linux"
#now we use cloud-init to initialize fedora vm
#password = "riscv" # not need before because we use pubkey before
#private_key_path = "~/.ssh/id_rsa"