#!/bin/bash

PACKAGE_NAME="apache2"
PACKAGE_VERSION=$(dpkg -l | grep $PACKAGE_NAME | head -n 1 | awk '{print $3}')
PACKAGE_PRETTY_NAME="Apache HTTP Server"
PACKAGE_TYPE="Web Server"
PACKAGE_DESCRIPTION="Apache HTTP Server"

echo $PACKAGE_VERSION
echo $PACKAGE_PRETTY_NAME
echo $PACKAGE_TYPE
echo $PACKAGE_DESCRIPTION
