name: Bianbu Test

on:
#   schedule:
#     - cron: '0 3 * * 1'  # 每周一凌晨3点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  test:
    runs-on: [self-hosted, linux]
    env:
      PRINT_SSH_MSG: 1
      RUST_LOG: debug
    permissions:
      contents: write
    steps:
    - name: Checkout dirty branch
      uses: actions/checkout@v2
      with:
        ref: 'dirty'
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev # lintestor build dependencies
        sudo apt-get install -y qemu-utils qemu-system-x86 qemu-system-misc opensbi u-boot-qemu
        sudo apt-get install -y sshpass
    
    - name: Setup Bianbu remote credentials with ACTIONS SECRETs
      env:
        BIANBU_IP: ${{ secrets.BIANBU_IP }}
        BIANBU_PORT: ${{ secrets.BIANBU_PORT }}
        BIANBU_USERNAME: ${{ secrets.BIANBU_USERNAME }}
        BIANBU_PASSWORD: ${{ secrets.BIANBU_PASSWORD }}
      run: |
        sed -i "s/{BIANBU_IP}/${BIANBU_IP}/" ./bianbu/config.toml
        sed -i "s/{BIANBU_PORT}/${BIANBU_PORT}/" ./bianbu/config.toml
        sed -i "s/{BIANBU_USERNAME}/${BIANBU_USERNAME}/" ./bianbu/config.toml
        sed -i "s/{BIANBU_PASSWORD}/${BIANBU_PASSWORD}/" ./bianbu/config.toml
    
    - name: Install & Run Lintestor
      run: |
        ls -l ../ # 展示上级文件结构
        ls -l . # 展示本级结构
        cargo install lintestor
        LATEST_BINARY=lintestor
        $LATEST_BINARY --test --aggr --summ
        rm .gitignore
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: bianbu-test-results
        path: |
          reports.json
          summary.md
    
    - name: Commit reports
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "test(report): Bianbu weekly test reports update"
        file_pattern: |
          **/*.json
          **/*/*.json
          summary.md
          reports.md