name: Clippy Check

on:
  push:
    branches: ["main"]  # Runs Clippy on every push to the `main` branch
  pull_request:
    branches: ["main"]  # Runs Clippy on every pull request targeting `main`

permissions:
  contents: read

jobs:
  clippy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Run Clippy
        run: cargo clippy -- -D warnings